#!/bin/sh

# input-remapper-control --command stop-all && input-remapper-control --command autoload
xset r rate 300 35
xset +dpms
xset s 900 900
export XCURSOR_SIZE=24
export XCURSOR_THEME=Breeze_Snow
export QT_STYLE_OVERRIDE=kvantum
export XDG_CURRENT_DESKTOP=awesome
export QT_QPA_PLATFORMTHEME=qt6ct
